title: "Elegant Equation: Drishti Bansal's Tech + Math + Art Journey"
description: "Exploring the intersection of technology, mathematics, and art through data science projects and visual storytelling."
author: "Drishti Bansal"
email: drishti2529@outlook.com
theme: minima
baseurl: ""
url: "https://dribansal25.github.io"

github_username: Dribansal25
linkedin_username: "www.linkedin.com/in/drishti-bansal"
